version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  django:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - REDIS_URL=redis://redis:6379/0
    build: ./backend
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  nextjs:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["npm", "run" ,"dev"]

  # 如果你需要Celery Beat:
  celerybeat:
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    build: ./backend
    command: celery -A backend beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
#      - ./ssl:/etc/ssl:ro  之後上伺服器後才需配置
    depends_on:
      - django
      - nextjs
